### ISSUE TITLE
[BUG] Instantly - New Event Instant failed

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#16958]
**Describe the bug**
The Campaign ID prop failed when using API Key v2
![Image](https://github.com/user-attachments/assets/d2dbd9e7-a3e9-4b73-98a9-0c986721a58b)

Please check all other place where we still use v1 API

**Additional context**
Raised by a connect customer

**Comment by jcortes** [comment]
Hi @vunguyenhung looking at the [repository](https://github.com/PipedreamHQ/pipedream/tree/master/components/instantly/sources) there is no such trigger named `New Event in Instantly (Instant)` as it is in the platform as this image shows

![Image](https://github.com/user-attachments/assets/2e07f013-fadf-4f11-911c-1ce4bae02668)

So in this case the component got deprecated and we need to remove it from PD as this [commit](https://github.com/PipedreamHQ/pipedream/commit/74dd14ff3d4278cd76186db6e400e9471305971b#diff-2cc8adaf1799ba0873ce787194551cc0b1096acc985edd3052287a6e6f626a9d) shows

Also I was trying to look at the endpoints [here](https://developer.instantly.ai/) and there is no support for webhooks (Instant)

All endpoints at this moment are using the latest version `https://api.instantly.ai/api/v2`

So I guess what we need to do here is to remove the component `New Event in Instantly (Instant)` since it got deprecated @sergio-eliot-rodriguez @dannyroosevelt 


Also an update to the node.js initial code is needed 

![Image](https://github.com/user-attachments/assets/3d12e381-b6c4-4d7d-9790-e094a6466d99)

Because it's showing this error:

![Image](https://github.com/user-attachments/assets/8e609da2-5db9-49d4-98de-8de9c7dc0bc2)
which can be fixed by replacing:
```
import { axios } from "@Pipedream/platform"
```
to:
```
import { axios } from "@pipedream/platform"
```

**Comment by dannyroosevelt** [comment]
Thanks for the heads up @jcortes. I fixed the code scaffolding, let's ignore the issue with the trigger not being in the repo for now. Can you take a look at the prop Leo pointed out?

**Comment by michelle0927** [comment]
> Thanks for the heads up [@jcortes](https://github.com/jcortes). I fixed the code scaffolding, let's ignore the issue with the trigger not being in the repo for now. Can you take a look at the prop Leo pointed out?

Hi @dannyroosevelt. All the Instantly components in the repo work without error for me, including the `campaignId` prop. The mysterious "New Event in Instantly (Instant)" trigger fails because it's sending the API key in `params` instead of in `headers`. As far as I can tell from the docs, @jcortes  is correct that the API doesn't support a way to create webhooks.

<img width="838" alt="Image" src="https://github.com/user-attachments/assets/5cc9c7be-8b7b-46ae-8292-55134163872b" />

<img width="384" alt="Image" src="https://github.com/user-attachments/assets/00cd6d3a-f943-4cf1-b39b-4866237c6bd8" />

```
    _baseUrl() {
      return "https://api.instantly.ai/api/v2";
    },
    _headers(headers = {}) {
      return {
        ...headers,
        Authorization: `Bearer ${this.$auth.api_key}`,
      };
    },
    _makeRequest({
      $ = this, headers, path, ...opts
    }) {
      return axios($, {
        url: this._baseUrl() + path,
        headers: this._headers(headers),
        ...opts,
      });
    },
```

**Comment by michelle0927** [comment]
@dannyroosevelt I probably forgot to ask that "New Event in Instantly (Instant)" be unpublished when I updated Instantly to v2 — that was likely my oversight.

**Comment by michelle0927** [comment]
@dannyroosevelt Shall I close this ticket? 
FYI, I can still see the "New Event in Instantly (Instant)" source listed in the UI.

<img width="555" alt="Image" src="https://github.com/user-attachments/assets/8f940141-d032-45ae-a902-239c8b601b66" />

**Comment by michelle0927** [comment]
@vunguyenhung Hi Leo! Would you be able to unpublish `instantly-new-event-instant` to get this ticket resolved?

**Comment by vunguyenhung** [comment]
Hey, I think only Pipedream engineer can unpublish a component by using a script.

Hello @andrewjschuang , could you please unpublish the component `Instantly - New Event in Instantly (Instant)`?

**Comment by vunguyenhung** [comment]
The component is unpublished. Closing now
