### ISSUE TITLE
[BUG] Can not create Salesforce Instant sources 

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#4166]
**Describe the bug**
First reported by a customer here: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1662346083419929
> Hi All - New to Pipedream. Considering adopting it as core part of our integration stack. However,
it seems I can't create a Salesforce source for instant updates (I have tried this with a few other tools and works just fine so I don't believe its permissions related). Keep getting "Create webook error"
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/18277920/188436413-80d8fe76-6a85-4b81-9740-9fa139901a14.png">

The customer also reported that he tried this with [n8n.io](http://n8n.io/), [tray.io](http://tray.io/), and AWS AppFlow, all work with instant style triggers. I've only had this issue with Pipedream.

**To Reproduce**
1. Access Pipedream > Source
2. Create a new Salesforce - New Object (Instant, of Selectable Type)
3. Observe error `UNKNOWN_EXCEPTION: admin operation already in progress`

**Expected behavior**
The source is created successfully.

**Comment by sweepy84** [comment]
Happy to provide some time to help debug this. Timezone - AEST

**Comment by vunguyenhung** [comment]
Hello @jverce, could I request your help for this issue 🙏 ?

@sweepy84 is evaluating Pipedream Enterprise plan and want to use our Salesforce Instant sources, though he have an issue on his side when creating the source that I couldn’t reproduce. 

Upon further checking, I see that our Pipedream instant source is using [`salesforce-webhooks` package (https://www.npmjs.com/package/salesforce-webhooks) that you authored, so I think you might be able to help 🙏

**Comment by dylburger** [comment]
I've asked @andrewjschuang to take a look at this. @sweepy84 also said that we fail to list custom objects in the Object Type field of the "Instant" sources. They appear to correctly appear in the list for the Selectable Type components. See https://pipedream-users.slack.com/archives/CPTJYRY5A/p1662596198836909 for more information.

**Comment by Hassan-Abbas-SQA** [comment]
for OLD salesforce New Object (instant , of scaleable type) iam able to create source/trigger successfully 
<img width="951" alt="image" src="https://user-images.githubusercontent.com/104946677/190416855-526df0ac-7f9c-472f-9999-31c88217836b.png">

TestCase on this new PR
i was able to create source , SObject type as Product ,Account etc...
![image](https://user-images.githubusercontent.com/104946677/190419663-63d9ecdc-c9b7-486f-bec2-d4638dee3211.png)


but i can’t create source when i select SObject type as AI insight action
![image](https://user-images.githubusercontent.com/104946677/190419548-0004633d-c344-4ca5-aad2-33df93a0301b.png)

**Comment by vunguyenhung** [comment]
Hello @dannyroosevelt @andrewjschuang, I'm able to create sources for standard object & custom object, and they work correctly
[Salesforce_4196_2350.pdf](https://github.com/PipedreamHQ/pipedream/files/9585851/Salesforce_4196_2350.pdf)

---

Though there're 2 cases need your attention
### Improvement needed: Initial Historical events are not emitted
When I deployed a new source, there’re no initial historical events when I first deployed the source
![FireShot Capture 304 - Pipedream - Connect APIs, Remarkably Fast - pipedream com](https://user-images.githubusercontent.com/18277920/190690040-71e5dd96-e60d-4582-9032-bfad4adaf3ff.png)

**Suggestion:** I suggest that we release this fix and create another Github issue for improvement

### Bug fix: the source can not be created - Skipped

Per the bug report here: [https://github.com/PipedreamHQ/pipedream/issues/4166#issue-1361779075](https://github.com/PipedreamHQ/pipedream/issues/4166#issue-1361779075), I can not reproduce the bug. Hence, I could not confirm that it has been fixed. 

**Suggestion:** I suggest that we release this and communicate with the user to test on his side after we released this

What do you think?

**Comment by sweepy84** [comment]
@dylburger @vunguyenhung @andrewjschuang - This issue persists for us. Unable to create any instant sources to salesforce. As mentioned in slack this has worked with the same salesforce instance/account with all other service providers I've tried. Happy to jump on a call to help resolve.

**Comment by andrewjschuang** [comment]
Hi @sweepy84, can you please check if there are any triggers configured?
If there are, would it be ok to delete them and try again?

![image](https://user-images.githubusercontent.com/15385076/191355618-222a9f2b-a9df-4cae-b8a6-1d4670dbd7fd.png)

**Comment by sweepy84** [comment]
Note for reference - It appears that when we try to create an Apex Class or Apex Trigger (2 things Pipedream Salesforce source requires) it fails with the below messages.
This appears to be something to do with Salesforce locking. A support ticket was raised. Will provide further updates for reference.

<img width="609" alt="image" src="https://user-images.githubusercontent.com/4423880/191628862-56ddca4f-b2c6-4149-9b6e-7d52cadbace0.png">
<img width="501" alt="image" src="https://user-images.githubusercontent.com/4423880/191628894-dd7db44b-42ee-4551-9959-8499113e3e12.png">
