### ISSUE TITLE
[BUG] Axios Error - Twitch Component Won't Execute Due to Error

### ISSUE THREAD

**Issue by clarkio** [PipedreamHQ/pipedream#4565]
**Describe the bug**
Using any of the Twitch components results in the action failing due to an error with Axios. After further investigation of the error I believe it's due to a recent change to the axios package which is noted in this issue in the Axios repo: https://github.com/axios/axios/issues/5142. This seems to require some changes to what's provided in the configuration object to the axios package - specifically the `paramsSerializer` option. This option requires a new key called `encode`.

```
AxiosError
options must be an object

DETAILS
    at Object.assertOptions 
```

> Note: see attached screen shot for error shown in my workflow

**To Reproduce**
1. Add any Twitch component to a workflow
2. Fill in all necessary fields for the Twitch component you chose
3. Test the action using the Twitch component
4. See the error

**Expected behavior**
Twitch actions to execute requests and return a result

**Screenshots**
<img width="912" alt="image" src="https://user-images.githubusercontent.com/6265396/197410373-0dc937c7-7d27-4971-aca1-dfcb646ed891.png">

**Desktop (please complete the following information):**
 - Browser: Brave
 - Version: Happy to share this but version of what? My browser? If so it's 1.44.112

**Additional context**
Axios seems to have made an update that's a breaking change based on this issue in their repo: 

I believe this function in the pipedream Twitch component code needs to be updated: https://github.com/PipedreamHQ/pipedream/blob/bdb6a86866a4400dbee0cdb487b783473dcbfe01/components/twitch/twitch.app.mjs#L53

This issue for the Axios docs covers what I believe needs to change: https://github.com/axios/axios-docs/issues/90

Before:
```
paramsSerializer: function (params) {
    return Qs.stringify(params, {arrayFormat: 'brackets'})
},
```

After:
```
paramsSerializer: {
    encode: function(params) {
        return Qs.stringify(params, {arrayFormat: 'brackets'})
    }
},
```

**Comment by dannyroosevelt** [comment]
Thank you so much for the detailed report and breakdown, @clarkio! FYI since it looks like you were in the component code, we're happy to review a PR if you're interested in implementing the fix yourself, otherwise our team will take a look soon.

**Comment by clarkio** [comment]
@dannyroosevelt thanks and yea I'd be happy to but I see there is a PR open which I'm also happy to see 👍

**Comment by dannyroosevelt** [comment]
Oops looks like we jumped the gun on it... but it's in the QA queue, so it should be fixed soon!

**Comment by Hassan-Abbas-SQA** [comment]
@clarkio TestPassed
![image](https://user-images.githubusercontent.com/104946677/197870888-f8491cc7-b7ca-4998-a908-0ba74e5ea2e4.png)

**Comment by clarkio** [comment]
This is great to see. Does it mean it's been published to the platform now as well? @Hassan-Abbas-SQA @lcaresia @dannyroosevelt

**Comment by lcaresia** [comment]
@clarkio Yes, it's published!

**Comment by clarkio** [comment]
@lcaresia great to hear. Is there anything I need to do in my workflows to get it updated? I noticed the error still showing up when I tried earlier.

**Comment by lcaresia** [comment]
> @lcaresia great to hear. Is there anything I need to do in my workflows to get it updated? I noticed the error still showing up when I tried earlier.

Yes, you need to remove the action and create again!

If you still having the problem call me on Slack and I will help you ☺️

**Comment by dannyroosevelt** [comment]
@clarkio you actually don't need to remove the action from your workflow -- you should see a red button at the top right of the Twitch step that says "Update".

**Comment by clarkio** [comment]
@dannyroosevelt I'm not seeing that option in my workflows. Here is an example:
![image](https://user-images.githubusercontent.com/6265396/198344747-fed15a46-13c9-4f78-9c9b-d9d07aa05128.png)

**Comment by dannyroosevelt** [comment]
Hey @clarkio that's strange. We aren't able to reproduce that issue. Can you try refreshing the page? If you still don't seen a prompt to **Update** the action, can you visit the settings for that workflow and enable the toggle to **Share with Support**, then paste the workflow URL so I can check it out?

**Comment by dannyroosevelt** [comment]
Actually, we were able to reproduce the error and we're looking into it. In the meantime if you want to get the action working asap, you can definitely remove that step and add it again.

**Comment by dannyroosevelt** [comment]
FYI we've identified the issue and confirmed it's not related to this Twitch update. We are tracking the issue re: not getting prompted to update existing actions [here](https://github.com/PipedreamHQ/pipedream/issues/4600).

**Comment by dannyroosevelt** [comment]
FYI @clarkio this should be fixed -- you should now be able to update actions normally
![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/198692753-463b5645-572c-4ad2-8807-67f362ab38ef.png)

**Comment by clarkio** [comment]
Awesome and thanks for sharing the update 🙂👍
